import './globals.css'

export const metadata = {
  title: 'Renan Gustavo - Desenvolvedor full stack',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className="bg-very-dark-gray">
        <header className="bg-dark-gray fixed z-50 w-full">
          <section className="flex items-center justify-between p-6 text-primary-white">
            <h1 className="text-2xl font-semibold">Portfólio</h1>

            <nav className="w-3/6 hidden md:block lg:w-1/3">
              <ul className="flex justify-between">
                <li><a href="">Sobre mim</a></li>
                <li><a href="">Projetos</a></li>
                <li><a href="">Serviços</a></li>
                <li><a href="">Minhas Skills</a></li>
              </ul>
            </nav>
          </section>
        </header>

        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
