import './globals.css';

import { DM_Sans } from 'next/font/google';
import { Header } from '@/components/Header';

const dm = DM_Sans({
  weight: ['400', '500', '700'],
  subsets: ['latin']
});

export const metadata = {
  title: 'Renan Gustavo - Desenvolvedor full stack',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className={dm.className}>
      <body className="bg-very-dark-gray">
        <Header />

          <main className="pt-28 px-8 xl:px-52 h-screen">
            {children}
          </main>
      </body>
    </html>
  );
}
